1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written and reusable code modules that provide a set of functions and methods to perform specific tasks. 
These libraries are designed to simplify and expedite the development process by providing ready-made solutions for common programming tasks.

Here are some key reasons why Python libraries are widely used:

1. Code Reusability: Libraries contain pre-built functions and modules that can be easily reused in different projects. This helps in saving time and 
effort by avoiding the need to reinvent the wheel for common tasks.

2. Productivity: Python libraries abstract complex functionalities, allowing developers to focus on higher-level tasks rather than dealing with low-level details.
This boosts productivity and accelerates the development process.

3. Community Contributions: Python has a large and active community of developers who contribute to the creation and maintenance of various libraries. 
This collaborative effort results in a rich ecosystem of libraries covering a wide range of domains and applications.

4. Specialized Functionality: Python libraries often provide specialized functionality in specific domains such as data analysis, machine learning, 
web development, scientific computing, etc. Leveraging these libraries allows developers to access advanced features without having to implement them from scratch.

5. Code Consistency: Libraries follow established coding standards and best practices, promoting code consistency. Developers can rely on these standards
when using library functions, ensuring a uniform and maintainable codebase.

6. Performance Optimization: Many Python libraries are implemented in low-level languages like C or C++, making them highly efficient. This allows developers
to benefit from optimized performance without sacrificing the simplicity of Python syntax.

7. Documentation and Support: Well-maintained libraries come with comprehensive documentation that includes usage guides, examples, and explanations
of functionality. Additionally, the community support for popular libraries is often robust, making it easier for developers to find solutions to common issues.

Overall, Python libraries contribute significantly to the language's popularity and versatility, enabling developers to build complex applications efficiently.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but there are several key differences between them. Here are some of the main distinctions:

1.  Type of Elements: 
   -  NumPy Array:  All elements in a NumPy array must be of the same data type. NumPy arrays are homogeneous, which means they can efficiently store and manipulate
      large datasets of a single data type (e.g., integers, floats).
   -  List:  Lists can contain elements of different data types. They are heterogeneous and can hold a mix of integers, floats, strings, or other Python objects.

2.  Performance: 
   -  NumPy Array:  NumPy arrays are more memory-efficient and faster than lists for numerical operations. NumPy is implemented in C and allows for vectorized operations,
      which means operations can be applied to entire arrays without the need for explicit looping in Python.
   -  List:  Lists are generally slower and consume more memory compared to NumPy arrays, especially for large datasets. They are more versatile but may be less efficient
      for numerical computations.

3.  Syntax and Functionality: 
   -  NumPy Array:  NumPy provides a variety of functions and methods specifically designed for array manipulation, mathematical operations, linear algebra, and statistical
      analysis. NumPy arrays support vectorized operations, making code concise and readable.
   -  List:  Lists are part of the core Python language and provide a more general-purpose way to store and manipulate data. However, they lack the specialized functions and
      optimizations that NumPy arrays offer for numerical computing.

4.  Size and Dimensions: 
   -  NumPy Array:  NumPy arrays can be multi-dimensional, allowing the representation of matrices and tensors. This is especially useful for numerical computations in linear
      algebra, machine learning, and scientific computing.
   -  List:  Lists are one-dimensional, and to represent multi-dimensional structures, nested lists are used. However, working with nested lists can be less convenient for 
      numerical operations.

5.  Memory Overhead: 
   -  NumPy Array:  NumPy arrays have less memory overhead compared to lists, as they store data more compactly and do not require extra information about data types for each
      element.
   -  List:  Lists have more memory overhead due to the flexibility of storing different data types and the need to store type information for each element.

In summary, NumPy arrays are optimized for numerical computations and are more memory-efficient and faster for such operations. Lists, on the other hand, are more versatile
and can store heterogeneous data types but are generally less efficient for numerical tasks. The choice between them depends on the specific requirements of the task at hand.

In [30]:
import numpy as np

my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

array_shape = my_array.shape
array_size = my_array.size
array_dimension = my_array.ndim

print("Array Shape:", array_shape)
print("Array Size:", array_size)
print("Array Dimension:", array_dimension)


Array Shape: (3, 4)
Array Size: 12
Array Dimension: 2


In [31]:
import numpy as np

my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

first_row = my_array[0, :]

print("First Row:", first_row)


First Row: [1 2 3 4]


In [32]:
import numpy as np

my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

row_column = my_array[2, 3]

print("3rd Row & 4th Column:", row_column)

3rd Row & 4th Column: 12


In [33]:
import numpy as np

my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

odd_indexed_elements = my_array[:, 1::2]

print("Odd-Indexed Elements:")
print(odd_indexed_elements)


Odd-Indexed Elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [34]:
import numpy as np

random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)


Random 3x3 Matrix:
[[0.44250002 0.11840755 0.90053573]
 [0.70085839 0.87748678 0.30385697]
 [0.23776892 0.34026268 0.17121285]]


8. Describe the difference between np.random.rand and np.random.randn?

1.  `np.random.rand`: 
   - This function generates random values from a uniform distribution over the interval [0, 1).
   - It takes dimensions as arguments, specifying the shape of the output array.
   - For example, `np.random.rand(2, 3)` would generate a 2x3 matrix with values between 0 and 1.

   ```python
   import numpy as np

   random_uniform = np.random.rand(2, 3)
   ```

2.  `np.random.randn`: 
   - This function generates random values from a standard normal distribution (mean = 0, standard deviation = 1).
   - It also takes dimensions as arguments, specifying the shape of the output array.
   - For example, `np.random.randn(2, 3)` would generate a 2x3 matrix with values sampled from a standard normal distribution.

   ```python
   import numpy as np

   random_normal = np.random.randn(2, 3)
   ```

In summary:
- `np.random.rand` generates values from a uniform distribution over [0, 1).
- `np.random.randn` generates values from a standard normal distribution.

Both functions are useful in different scenarios, depending on the type of random values you need for your application.

In [35]:
import numpy as np

original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

expanded_array = np.expand_dims(original_array, axis=0)

print("Original Array:")
print(original_array)

print("\nExpanded Array:")
print(expanded_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [36]:
import numpy as np

original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

transposed_array = original_array.T

print("Original Array:")
print(original_array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

1.Index Wise Multiplication.
2. Matrix multiplication.
3. Add both the matrics.
4. Subtact matix B from A.
5. Divide Matix B by A

In [37]:
import numpy as np

matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index Wise Multiplication
index_wise_multiplication = matrix_A * matrix_B

# 2. Matrix Multiplication
matrix_multiplication = np.dot(matrix_A, matrix_B.T)  # Transpose of matrix_B to match dimensions

# 3. Add both matrices
matrix_addition = matrix_A + matrix_B

# 4. Subtract matrix B from A
matrix_subtraction = matrix_A - matrix_B

# 5. Divide matrix B by A (element-wise division)
matrix_division = np.divide(matrix_B, matrix_A)

# Display the results
print("1. Index Wise Multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

print("\n3. Matrix Addition:")
print(matrix_addition)

print("\n4. Matrix Subtraction:")
print(matrix_subtraction)

print("\n5. Matrix Division:")
print(matrix_division)


1. Index Wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix Division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [38]:
import numpy as np

original_array = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_array = original_array.byteswap()

print("Original Array:", original_array)
print("Swapped Array:", swapped_array)



Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a matrix. The significance of this function is particularly evident in linear algebra, 
where finding the inverse of a matrix is essential for solving systems of linear equations and other mathematical operations.

14. What does the np.reshape function do, and how is it used?

In [39]:
# The np.reshape function in NumPy is used to change the shape of an array. It returns a new array with the same data but a different shape.

import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

In [40]:
# Broadcasting in NumPy refers to the ability of universal functions (ufuncs) to operate on arrays of different shapes and sizes. It allows NumPy to perform 
# element-wise operations on arrays of different shapes without explicitly creating additional copies of the data.


import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = 2.0

result = a * b  # The scalar b is broadcast to the shape of a

print("Array a:", a)
print("Scalar b:", b)
print("Result:", result)


Array a: [1. 2. 3.]
Scalar b: 2.0
Result: [2. 4. 6.]
