In [1]:
import numpy as np
arr = np.ones((3,4))

In [2]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [4]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [5]:
np.empty((3,4), int)  ##Gives array with different value each time

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [6]:
np.empty((3,4)) 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [7]:
np.eye(3) ##Return a 2-D array with ones on the diagonal and zeros elsewhere.
#To calculate Inverse Of a Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(3, dtype = int) ##n*n matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
import pandas as pd

In [10]:
##dataframe - rows and column

In [11]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [12]:
#Extra
import random #it is a module in python
random.choice((1,2,3,4,5,6)) #give different value while executing again and again
random.choice('Amit')

random.randrange(1,1000) #gives random value between given range
random.random() #random number generated between (0 and 1 excluded) 
lis = [1,2,3,4,5]
random.shuffle(lis)
lis
random.uniform(7,14) #number in between range uniformly

7.410642753169549

In [13]:
#The above samething will be done by Numpy like this

In [14]:
np.random.rand(2,3)

array([[0.96463074, 0.38818034, 0.87908827],
       [0.50747635, 0.65248051, 0.9537874 ]])

In [15]:
np.random.rand(1)

array([0.10768728])

In [16]:
np.random.randn(2,3)

array([[-0.54044441,  0.11934089,  0.94614472],
       [ 0.53808777,  0.33820306, -1.95220197]])

In [17]:
np.random.random_sample()

0.7920554952146943

In [18]:
np.random.randint(1,5, size = (3,4))

array([[1, 3, 1, 3],
       [2, 1, 3, 1],
       [3, 2, 1, 1]])

In [19]:
arr = np.random.randint(1,5, size = (3,4))

In [20]:
arr

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [21]:
arr.size

12

In [22]:
arr.shape

(3, 4)

In [23]:
arr.ndim

2

In [24]:
arr.reshape(2,6)

array([[2, 4, 4, 4, 1, 4],
       [2, 4, 3, 3, 4, 3]])

In [25]:
arr.reshape(3,4)

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [26]:
arr.reshape(4,-1)

array([[2, 4, 4],
       [4, 1, 4],
       [2, 4, 3],
       [3, 4, 3]])

In [27]:
arr.reshape(4,-10000)

array([[2, 4, 4],
       [4, 1, 4],
       [2, 4, 3],
       [3, 4, 3]])

In [28]:
arr.reshape(-1,3)

array([[2, 4, 4],
       [4, 1, 4],
       [2, 4, 3],
       [3, 4, 3]])

In [29]:
arr.reshape(3,4).base

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [30]:
arr.reshape(12,1).base

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [31]:
arr.reshape(6,2).base

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [32]:
##.base gives you original matrix

In [33]:
arr

array([[2, 4, 4, 4],
       [1, 4, 2, 4],
       [3, 3, 4, 3]])

In [34]:
arr.reshape(2,2,3)  # 2, 2 rows, 3 col, 3dimension

array([[[2, 4, 4],
        [4, 1, 4]],

       [[2, 4, 3],
        [3, 4, 3]]])

In [35]:
arr.reshape(4,3,1)

array([[[2],
        [4],
        [4]],

       [[4],
        [1],
        [4]],

       [[2],
        [4],
        [3]],

       [[3],
        [4],
        [3]]])

In [36]:
lis = [1,2,3,4]
arr =  np.array(lis)

In [37]:
arr

array([1, 2, 3, 4])

In [38]:
arr.ndim

1

In [39]:
arr2 = np.array([[2,3], [4,5]])

In [40]:
arr2

array([[2, 3],
       [4, 5]])

In [41]:
arr2.ndim

2

In [42]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
arr2.ndim

2

In [44]:
arr3 = np.zeros((1,3,4)) #3rows, 4 col, 1dimension
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [45]:
arr3.ndim

3

In [46]:
arr4 = np.zeros((1,1,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [47]:
arr4.ndim

4

In [48]:
arr4.shape

(1, 1, 3, 4)

In [49]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
arr3.ndim

3

In [51]:
arr3.shape

(2, 3, 4)

In [52]:
arr1 = np.random.randint(1,10,(5,6))

In [53]:
arr1

array([[2, 3, 7, 9, 3, 4],
       [9, 6, 7, 9, 4, 1],
       [2, 3, 9, 8, 5, 5],
       [7, 6, 3, 7, 6, 8],
       [3, 2, 4, 1, 2, 6]])

In [54]:
arr1>5

array([[False, False,  True,  True, False, False],
       [ True,  True,  True,  True, False, False],
       [False, False,  True,  True, False, False],
       [ True,  True, False,  True,  True,  True],
       [False, False, False, False, False,  True]])

In [55]:
arr1[arr1>5]

array([7, 9, 9, 6, 7, 9, 9, 8, 7, 6, 7, 6, 8, 6])

In [56]:
arr

array([1, 2, 3, 4])

In [57]:
arr[0]

1

In [58]:
arr[1]

2

In [59]:
arr1

array([[2, 3, 7, 9, 3, 4],
       [9, 6, 7, 9, 4, 1],
       [2, 3, 9, 8, 5, 5],
       [7, 6, 3, 7, 6, 8],
       [3, 2, 4, 1, 2, 6]])

In [60]:
arr1[2][3]

8

In [61]:
arr1[0][1:4]

array([3, 7, 9])

In [62]:
arr1[0, 1:4]

array([3, 7, 9])

In [63]:
arr1[0, [1,4]]

array([3, 3])

In [64]:
arr1[0, [1,5]]   #not slicing gives particular values only

array([3, 4])

In [65]:
arr1[2:4, 3:5]  #Gives slicing values

array([[8, 5],
       [7, 6]])

In [66]:
arr1[2:4]

array([[2, 3, 9, 8, 5, 5],
       [7, 6, 3, 7, 6, 8]])

In [67]:
arr1[0, 3:5]

array([9, 3])

In [68]:
arr1

array([[2, 3, 7, 9, 3, 4],
       [9, 6, 7, 9, 4, 1],
       [2, 3, 9, 8, 5, 5],
       [7, 6, 3, 7, 6, 8],
       [3, 2, 4, 1, 2, 6]])

In [69]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [71]:
arr1

array([[1, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [72]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [2, 1, 2]])

In [73]:
arr1+arr2

array([[2, 3, 4],
       [2, 4, 3],
       [3, 2, 4]])

In [74]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  0, -1],
       [-1,  0,  0]])

In [75]:
arr1*arr2

array([[1, 2, 4],
       [1, 4, 2],
       [2, 1, 4]])

In [77]:
arr1@arr2  ##matix multiplication

array([[6, 6, 8],
       [5, 7, 8],
       [6, 6, 8]])

In [78]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 1. , 0.5],
       [0.5, 1. , 1. ]])

# Brodcasting

In [79]:
arr = np.zeros((3,4))

In [80]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [82]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
a = np.array([1,2,3,4])

In [85]:
a

array([1, 2, 3, 4])

In [86]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [87]:
a = np.array([1,2,3])

In [88]:
a

array([1, 2, 3])

In [90]:
arr+a  ##dimension not same

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [94]:
a = np.array([[1,2,3]])

In [95]:
a

array([[1, 2, 3]])

In [96]:
a.T  ## Transpose

array([[1],
       [2],
       [3]])

In [97]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [98]:
a.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [99]:
a = np.array([1,2,3])

In [100]:
a.T

array([1, 2, 3])

In [101]:
arr1

array([[1, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [106]:
np.sqrt(arr1)  ##Square root

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356]])

In [107]:
np.log10(arr1)  ##log value

array([[0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.30103]])

In [108]:
np.exp(arr1)  ##Exponential Value

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [109]:
np.min(a)

1

In [110]:
np.max(a)

3

In [111]:
arr1

array([[1, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [112]:
arr1.T

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [113]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
arr = np.array([[1,2,3], [4,5,6],[1,2,3]])

In [119]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [120]:
np.sum(arr)

27

In [123]:
np.sum(arr, axis=0)   ##column wise sum axis=0

array([ 6,  9, 12])

In [124]:
np.sum(arr, axis=1) ##row wise sum axis=1

array([ 6, 15,  6])

In [126]:
#expand_dims>> expand the array by inserting a new array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [127]:
arr.ndim

1

In [129]:
arr1 = np.expand_dims(arr, axis=0)

In [131]:
arr1  ##now it's 2D

array([[1, 2, 3, 4]])

In [132]:
arr1.ndim

2

In [133]:
arr2 = np.expand_dims(arr1, axis=0)

In [134]:
arr2

array([[[1, 2, 3, 4]]])

In [136]:
arr2.ndim

3

In [137]:
arr2.shape

(1, 1, 4)

In [138]:
arr1 = np.expand_dims(arr, axis=1)

In [139]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [140]:
arr = np.zeros((3,4))

In [141]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
arr1 = np.expand_dims(arr, axis=0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [143]:
arr1 = np.expand_dims(arr, axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])