In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [4]:
##Why numpy

# 1. Mathematical Function
# 2. Faster

In [5]:
l = [1,2,3,4,5]

In [6]:
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
type(np.array(l))

numpy.ndarray

In [8]:
arr  = np.array(l)

In [9]:
arr.ndim

1

In [10]:
l = [1,2,3,4,5, "Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U21')

In [11]:
arr1.ndim

1

In [12]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.ndim

2

In [15]:
type(np.array(np.array([[1,2,3], [4,5,6]])))

numpy.ndarray

In [16]:
arr1.ndim

2

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr1.ndim

2

In [21]:
l = [1,2,3,4]

In [22]:
l

[1, 2, 3, 4]

In [23]:
mat = np.matrix(l)

In [24]:
#Matrix is always 2 Dimensional

In [25]:
np.array(l)

array([1, 2, 3, 4])

In [26]:
### By defau;t matrix is 2d

In [27]:
np.matrix([[[1,2], [3,4], [7,8]]])

ValueError: matrix must be 2-dimensional

In [28]:
##matrix must be 2-dimensional

In [29]:
np.array([[[1,2], [3,4], [7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [30]:
##This is 3d

In [31]:
#more way to do 3d

In [32]:
np.asarray([[[1,2], [3,4], [7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [33]:
##matrix is a subarray of array

In [34]:
np.asanyarray([[[1,2], [3,4], [7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [35]:
##This is also to convert into array

In [36]:
mat

matrix([[1, 2, 3, 4]])

In [37]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [38]:
##not converted into array it is in matrix only

In [39]:
##matrix is subclass of an array

In [40]:
np.asarray([[[1,2], [5,6], [7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [41]:
np.array([[[1,2], [3,4], [7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [42]:
t = ([1,2,3], [4,5,6])

In [43]:
type(t)

tuple

In [44]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a=5
np.array(a)

array(5)

In [46]:
##array is faster than list

In [47]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [48]:
arr[0]

1

In [49]:
arr[3]

4

In [50]:
a = arr  ##shallow copy

In [51]:
a

array([1, 2, 3, 4, 5])

In [52]:
arr[0] = 1000

In [53]:
arr

array([1000,    2,    3,    4,    5])

In [54]:
a

array([1000,    2,    3,    4,    5])

In [55]:
b = a.copy()  ##deep copy

In [56]:
b

array([1000,    2,    3,    4,    5])

In [57]:
b[0] = 2000

In [58]:
b

array([2000,    2,    3,    4,    5])

In [59]:
a

array([1000,    2,    3,    4,    5])

In [60]:
##Multiple ways to generate arrays

In [61]:
np.fromfunction(lambda i, j : i==j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr.shape

(5,)

In [64]:
arr1.shape

(2, 3)

In [65]:
arr

array([1000,    2,    3,    4,    5])

In [66]:
arr.shape

(5,)

In [67]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr1.shape

(2, 3)

In [69]:
arr1.size

6

In [70]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [71]:
range(5)

range(0, 5)

In [72]:
for i in range(5):
    print(i, end = " ")

0 1 2 3 4 

In [73]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [74]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [75]:
list(range(5))

[0, 1, 2, 3, 4]

In [76]:
iterable = (i*i for i in range(5))

In [77]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [78]:
np.fromstring('23 34 67', sep = ' ' )

array([23., 34., 67.])

In [79]:
np.fromstring('23, 34, 67', sep = ', ' )

array([23., 34., 67.])

In [80]:
np.fromstring('Aashu Amit Raj', sep = ',' )

/tmp/ipykernel_110/3911461001.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Aashu Amit Raj', sep = ',' )


array([], dtype=float64)

In [81]:
l = [1,2,3]
arr = np.array(l)
arr.dtype

dtype('int64')

In [82]:
arr

array([1, 2, 3])

In [83]:
range(5)

range(0, 5)

In [84]:
list(range(5))

[0, 1, 2, 3, 4]

In [85]:
list(range(1.0, 2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [86]:
## Range can't deal with float

In [89]:
np.arange(0.1, 10.2, 0.2) #number between 0.1 to 10.2 and 0.2 step of every number

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [90]:
np.linspace(1,5,20) #number between 1 to 5 and total 20 number

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [93]:
np.logspace(1,5, 10, base = 2) #give log value with equal space

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [98]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [97]:
arr2 = np.zeros((3,4))

In [99]:
arr2.shape

(3, 4)

In [101]:
arr2.ndim

2

In [102]:
arr3 = np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [103]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [104]:
arr3.ndim

3

In [106]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [108]:
arr = np.ones((3,4))

In [109]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [110]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [111]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [113]:
#1D - Vector
#2D - Matrix
#3D- Tensor