In [1]:
import numpy as np
data = np.array([[1],[2],[3]])

In [2]:
data.ndim

2

In [3]:
data

array([[1],
       [2],
       [3]])

In [7]:
a = np.squeeze(data)  #To reduce dimension of array

In [8]:
a.ndim

1

# Repeat

In [9]:
data

array([[1],
       [2],
       [3]])

In [15]:
np.repeat(data, 4)  # Repeat elements of an array in 1D

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
a = np.array([[1,2], [3,4]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [19]:
np.repeat(a,2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [20]:
np.repeat(a,2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [21]:
data

array([[1],
       [2],
       [3]])

In [22]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [23]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [24]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [25]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.roll(data,-1)

array([[2],
       [3],
       [1]])

In [32]:
a = np.array([[[1,2], [3,4], [5,6]]])

In [33]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [36]:
np.roll(a, 1, axis=0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [37]:
np.roll(a, 1, axis=1)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

# Binary Operation on array

In [38]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [41]:
arr1

array([[4, 9, 8, 3],
       [5, 7, 9, 9],
       [2, 9, 1, 5]])

In [42]:
arr2

array([[3, 7, 3, 3],
       [6, 4, 2, 7],
       [3, 3, 4, 3]])

In [43]:
arr1 + arr2

array([[ 7, 16, 11,  6],
       [11, 11, 11, 16],
       [ 5, 12,  5,  8]])

In [44]:
arr1*arr2

array([[12, 63, 24,  9],
       [30, 28, 18, 63],
       [ 6, 27,  4, 15]])

In [45]:
arr1/arr2

array([[1.33333333, 1.28571429, 2.66666667, 1.        ],
       [0.83333333, 1.75      , 4.5       , 1.28571429],
       [0.66666667, 3.        , 0.25      , 1.66666667]])

In [46]:
arr1-arr2

array([[ 1,  2,  5,  0],
       [-1,  3,  7,  2],
       [-1,  6, -3,  2]])

In [47]:
arr1**arr2

array([[     64, 4782969,     512,      27],
       [  15625,    2401,      81, 4782969],
       [      8,     729,       1,     125]])

In [48]:
arr1 > arr2

array([[ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True, False,  True]])

In [49]:
~arr1

array([[ -5, -10,  -9,  -4],
       [ -6,  -8, -10, -10],
       [ -3, -10,  -2,  -6]])

In [50]:
arr1

array([[4, 9, 8, 3],
       [5, 7, 9, 9],
       [2, 9, 1, 5]])

# Numpy string Function

In [51]:
arr = np.array(["PW", "Skills"])

In [52]:
arr

array(['PW', 'Skills'], dtype='<U6')

In [54]:
np.char.upper(arr)  ##convert in uppercase all letters

array(['PW', 'SKILLS'], dtype='<U6')

In [55]:
np.char.upper(np.array(["Amit"]))

array(['AMIT'], dtype='<U4')

In [57]:
np.char.capitalize(arr)  ##first letter capital

array(['Pw', 'Skills'], dtype='<U6')

In [59]:
np.char.title(arr)  ##first letter capital

array(['Pw', 'Skills'], dtype='<U6')

# Mathematical Function

In [60]:
arr1

array([[4, 9, 8, 3],
       [5, 7, 9, 9],
       [2, 9, 1, 5]])

In [61]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849,  0.98935825,  0.14112001],
       [-0.95892427,  0.6569866 ,  0.41211849,  0.41211849],
       [ 0.90929743,  0.41211849,  0.84147098, -0.95892427]])

In [62]:
np.cos(arr1)

array([[-0.65364362, -0.91113026, -0.14550003, -0.9899925 ],
       [ 0.28366219,  0.75390225, -0.91113026, -0.91113026],
       [-0.41614684, -0.91113026,  0.54030231,  0.28366219]])

In [63]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566, -6.79971146, -0.14254654],
       [-3.38051501,  0.87144798, -0.45231566, -0.45231566],
       [-2.18503986, -0.45231566,  1.55740772, -3.38051501]])

In [64]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.90308999, 0.47712125],
       [0.69897   , 0.84509804, 0.95424251, 0.95424251],
       [0.30103   , 0.95424251, 0.        , 0.69897   ]])

In [65]:
np.exp(arr1)

array([[5.45981500e+01, 8.10308393e+03, 2.98095799e+03, 2.00855369e+01],
       [1.48413159e+02, 1.09663316e+03, 8.10308393e+03, 8.10308393e+03],
       [7.38905610e+00, 8.10308393e+03, 2.71828183e+00, 1.48413159e+02]])

In [68]:
np.power(arr1,2)

array([[16, 81, 64,  9],
       [25, 49, 81, 81],
       [ 4, 81,  1, 25]])

In [69]:
np.mean(arr1)

5.916666666666667

In [70]:
np.max(arr1)

9

In [71]:
np.std(arr1)

2.8418988174966553

In [72]:
np.var(arr1)

8.076388888888888

In [73]:
arr1

array([[4, 9, 8, 3],
       [5, 7, 9, 9],
       [2, 9, 1, 5]])

In [74]:
arr2

array([[3, 7, 3, 3],
       [6, 4, 2, 7],
       [3, 3, 4, 3]])

In [75]:
arr1-arr2

array([[ 1,  2,  5,  0],
       [-1,  3,  7,  2],
       [-1,  6, -3,  2]])

In [76]:
np.subtract(arr1,arr2)

array([[ 1,  2,  5,  0],
       [-1,  3,  7,  2],
       [-1,  6, -3,  2]])

In [77]:
arr1*arr2

array([[12, 63, 24,  9],
       [30, 28, 18, 63],
       [ 6, 27,  4, 15]])

In [78]:
np.multiply(arr1,arr2)

array([[12, 63, 24,  9],
       [30, 28, 18, 63],
       [ 6, 27,  4, 15]])

In [81]:
np.mod(arr1,arr2)  ##return element wise

array([[1, 2, 2, 0],
       [5, 3, 1, 2],
       [2, 0, 1, 2]])

In [82]:
np.power(arr1,arr2)

array([[     64, 4782969,     512,      27],
       [  15625,    2401,      81, 4782969],
       [      8,     729,       1,     125]])

In [83]:
np.sqrt(arr1)

array([[2.        , 3.        , 2.82842712, 1.73205081],
       [2.23606798, 2.64575131, 3.        , 3.        ],
       [1.41421356, 3.        , 1.        , 2.23606798]])

## Sort and Search

In [85]:
arr = np.array([5,6,1,2])

In [86]:
arr

array([5, 6, 1, 2])

In [87]:
np.sort(arr)

array([1, 2, 5, 6])

In [88]:
np.searchsorted(arr,3)

4

In [90]:
arr1 = np.array([0,1,2,3,0,4])

In [91]:
np.count_nonzero(arr1)

4

In [92]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [93]:
np.where(arr1>0)

(array([1, 2, 3, 5]),)

In [94]:
np.extract(arr1>0, arr1)

array([1, 2, 3, 4])

In [95]:
arr = np.array([5,6,1,2,8,9])

In [96]:
arr

array([5, 6, 1, 2, 8, 9])

In [98]:
np.sort(arr)

array([1, 2, 5, 6, 8, 9])

In [99]:
np.searchsorted(arr,7)

4

In [100]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

## Matrix

In [101]:
#Matrix >> 2D array

In [102]:
import numpy.matlib as nm

In [103]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [105]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
#Numpy linear algebra

In [107]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [108]:
arr1

array([[9, 9, 9, 7],
       [2, 3, 9, 9],
       [4, 9, 6, 2]])

In [109]:
arr2

array([[5, 3, 4, 5],
       [4, 3, 7, 8],
       [8, 8, 4, 5]])

In [111]:
arr1 = np.array([[2,3], [4,5]])
arr2 = np.array([[1,3], [4,5]])

In [112]:
arr1@arr2

array([[14, 21],
       [24, 37]])

In [113]:
a = np.array([[7,5,-3], [3,-5,2], [5,3,-7]])

In [114]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [115]:
b = np.array([16,-8,0])

In [116]:
b

array([16, -8,  0])

In [117]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [118]:
arr1

array([[2, 3],
       [4, 5]])

In [119]:
5*2-3*4

-2

In [120]:
np.linalg.det(arr1)

-2.0

In [121]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])